### ISSUE TITLE
always using default namespace?

### ISSUE THREAD

**Issue by jonsalvas** [knight42/krelay#5]
First of all: Thanks for the awesome plugin, this is exactly what I need. 

Unfortunately I am a bit stuck, because a `kubectl relay' seems to always create a deployment in the default namespace, for which I don't have access to. Is there a way to specify the target namespace somehow (-n is ignored)?

```
I0413 08:27:51.904065    1474 main.go:142] "Check if krelay-server exists"
Error: ensure krelay-server: get krelay-server: deployments.apps "krelay-server" is forbidden: User "u-fnkzi4b3ce" cannot get resource "deployments" in API group "apps" in the namespace "default"
```

Command was:

```
kubectl relay -n mynamespace host/my.host.com 6333
```
Thanks!

**Comment by knight42** [comment]
@jonsalvas Hi! I am glad that you find this plugin useful ❤️ !

Regarding to your question,  the flag `-n` represents the namespace of the target object(such as Service, Pod). I think we could add a new flag, like `--server-namespace`, to override the current hard-coded `default` namespace.

Nevertheless some required permissions must be granted to use this plugin. If you only want to forward traffic to a hostname, please make sure the following permissions is granted
```
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/portforward
  verbs:
  - create
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - watch
```
